=== mat813/freebsd-doc/en/commercial/entries.dtd
<!-- DTD for commercial gallery entries on the FreeBSD website. -->
<!-- $FreeBSD$ -->

<!ELEMENT entries (cvs:keywords?, entry+)>

<!ELEMENT entry (name, url, description)>
<!ATTLIST entry id ID #REQUIRED>
<!ATTLIST entry continent (africa | asia | australia
	| europe | nzealand | namerica | samerica) #IMPLIED>

<!ATTLIST entry category (DATABASE | DEV | ECOMMERCE | EMAIL
	| MISC | MULTIMEDIA | NETWORK | SCIENTIFIC | SECURITY | SYSADMIN) #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT description (#PCDATA|a|b|i|tt|em|p|strong|img|ul)*>

<!-- misc HTML tags -->
<!ELEMENT a (#PCDATA|img)*>
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT b (#PCDATA|a)*>
<!ELEMENT i (#PCDATA|a)*>
<!ELEMENT tt (#PCDATA|a)*>
<!ELEMENT em (#PCDATA|a)*>
<!ELEMENT p (#PCDATA|a)*>
<!ELEMENT strong (#PCDATA|a)*>
<!ELEMENT ul (li)*>
<!ELEMENT li (#PCDATA|a)*>
<!ELEMENT img (#PCDATA|a)*>
<!ATTLIST img alt CDATA #IMPLIED>
<!ATTLIST img src CDATA #REQUIRED>

<!-- common cvs tags -->
<!ELEMENT cvs:keywords (cvs:keyword+)>
<!ATTLIST cvs:keywords xmlns:cvs CDATA #FIXED 'http://www.FreeBSD.org/XML/CVS'>
<!ATTLIST cvs:keywords version CDATA #FIXED '1.0'>

<!ELEMENT cvs:keyword (#PCDATA)>
<!ATTLIST cvs:keyword name CDATA #REQUIRED>

=== mat813/freebsd-doc/en/commercial/misc.xml
<?xml version="1.0"?>
<!DOCTYPE entries SYSTEM "entries.dtd">

<entries>
  <cvs:keywords xmlns:cvs="http://www.FreeBSD.org/XML/CVS" version="1.0">
    <cvs:keyword name="freebsd">
      $FreeBSD: www/en/commercial/misc.xml,v 1.2 2004/07/14 21:34:39 simon Exp $
    </cvs:keyword>
  </cvs:keywords>

  <entry id="Bookpool">
    <name>Bookpool</name>
    <url>http://www.bookpool.com/</url>
    <description>
      The Bookpool offers 30% discounts on the new edition of The
      Design and Implementation of the 4.4BSD Operating System and
      other FreeBSD-related books.
    </description>
  </entry>

  <entry id="BSDMall">
    <name>BSDMall</name>
    <url>http://www.bsdmall.com/</url>
    <description>
      BSDMall supports all flavors of BSD, providing books, clothing,
      hardware, software, and more!
    </description>
  </entry>

  <entry id="DOSSIER">
    <name>DOSSIER</name>
    <url>http://www.ptf.com/dossier/</url>
    <description>
      DOSSIER is a series of demand-printed document collections, covering
      a variety of Free and Open Source topics. DOSSIER uses FreeBSD
      documentation as the basis for many of its volumes.
    </description>
  </entry>

  <entry id="FreeBSDMall">
    <name>FreeBSD Mall</name>
    <url>http://www.freebsdmall.com/</url>
    <description>
      The FreeBSD Mall can provide everything you may want or need to
      enhance your FreeBSD experience. Are you new to FreeBSD? Or, perhaps
      you've been using it for years? We have something for you. We have
      the latest FreeBSD CDROMs, helpful books, and colorful shirts and
      hats. Stay current with FreeBSD and put it to work for you!
    </description>
  </entry>

  <entry id="Liebscher">
    <name>Liebscher &amp; Partner</name>
    <url>http://www.freibergnet.de</url>
    <description>
      Liebscher &amp; Partner are now shipping the BSD <a
      href="http://lem.freibergnet.de/cgi-bin/fanshop/scan/sf=category/se=BSD">
        Stuffed Daemon! <img alt="stuffed daemon" src="../gifs/plueschtier-tiny.jpg"/></a>
    </description>
  </entry>

  <entry id="Marketbridge">
    <name>Marketbridge Technologies, Inc.</name>
    <url>http://www.marketbridge.com/courses_freebsd.php</url>
    <description>
      At Marketbridge Technologies, Inc. we believe that courses with
      unsurpassed quality can be offered at reasonable rates. Don't
      break your training budget... come and see us first!  We are
      located in Ottawa, Canada and a stone throw away from downtown
      (a map is available on our website).  Call us at 1-877-595-5504
      or 1-613-728-5504.  We provide FreeBSD training.  Here's what
      you get: Manual: BSD Hacks, by Dru Lavigne, O'Reilly, ISBN
      0596006799, Instructor-Led Course, One PC per student, Duration:
      40 hours (all students welcomed to come back for practice given
      enough space in a class).
    </description>
  </entry>

  <entry id="ScotGold">
    <name>ScotGold Products</name>
    <url>http://www.scotgold.com/daemon.htm</url>
    <description>
      ScotGold Products design and manufacture PC case badges, including a
      BSD daemon badge with the permission and blessing of Kirk McKusick.
    </description>
  </entry>

  <entry id="FultusFODL">
    <name>Fultus FODL</name>
    <url>http://www.fultus.com/</url>
    <description>
      Fultus presents <a
      href="http://elibrary.fultus.com/mergedProjects/FreeBSD%20Documentati
      on/index.htm">FreeBSD Open Documentation Library</a>. This is the
      <b>full up-to-date</b> FreeBSD documentation collection available
      online in the Technical Literature section of the Fultus <a
      href="http://elibrary.fultus.com/">eLibrary</a> and Fultus Online
      Book <a
      href="http://store.fultus.com/advanced_search_result.php?keywords=Fre
      eBSD">Superstore</a> in the following formats:
      <ul>
	<li>Online Web Help (searchable through all documents)
	  (Mozilla, Netscape Navigator &amp; IE compatible);</li>
	<li>Searchable Adobe PDF format with Bookmark link page (for desktop
	  and PDA);</li>
	<li>Compiled HTML format (chm) (for Windows).</li>
      </ul>
      Interested? Read about FreeBSD eBooks and download examples on
      the <a href="http://www.fultus.com/free/documentation.phtml">FreeBSD
      Documentation</a> page of the <a href="http://www.fultus.com/">Fultus
      web site</a>.
    </description>
  </entry>

  <entry id="linuxdist">
    <name>LinuxDist</name>
    <description>
      LinuxDist sells Linux and BSD cds at very reasonable prices.
      We offer same day shipping on orders recieved before 1:00PM,
      we have low shipping rates, no hidden cost, and friendly service!
    </description>
  </entry>  
</entries>
